export const Color = [
    { name: 'pink' },
    { name: 'green' },
    { name: 'purple' },
    { name: 'violet' },
    { name: 'red' },
    { name: 'orange' },
    { name: 'cyan' },
    { name: 'yellow' },
    { name: 'blue' },
    { name: 'brown' },
    { name: 'gray' },
    { name: 'black' },
    { name: 'white' },
];
